### PR TITLE
Imx8mm updates - build fixes

### PR DESCRIPTION
**Pull request by acostach**

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
Hi @rcooke-warwick, need your help with this testbot 65e525df11236ed7e4f952fbd325ded0 for which the testbot app keeps restarting. Should I re-provision the Fin in it?

Same for the iot-gate-imx8 one https://dashboard.balena-cloud.com/devices/f42593ccda94ff06b11a2c425e7ccf89 but this is an Autokit

**Comment by acostach** [comment]
With this version WiFI AP WMM is enabled, and iPhone connectivity to the AP also works as expected.

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci retest this please

**Comment by acostach** [comment]
@balena-ci retest this please

**Comment by acostach** [comment]
@balena-ci retest this please

**Pull request merged**
