### PR TITLE
base-files: Remove append, mask Variscite issue file

### PR DESCRIPTION
**Pull request by acostach**
The /etc/issue file should not be empty for the
tests to pass

Signed-off-by: Alexandru Costache <alexandru@balena.io>
Changelog-entry: base-files: Remove append, mask Variscite issue file

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@acostach looks like issue file is populated - although the test still fails, now I think its because the issue file contains some extra stuff that the test isn't expecting (variscite logo in ascii):
```
cat /etc/issue
__      __        _          _ _
\\ \\    / /       (_)        (_) |
 \\ \\  / /_ _ _ __ _ ___  ___ _| |_ ___
  \\ \\/ / _` | '__| / __|/ __| | __/ _ \\
   \\  / (_| | |  | \\__ \\ (__| | ||  __/
    \\/ \\__,_|_|  |_|___/\\___|_|\\__\\___|

          2021 Variscite, Ltd.

balenaOS 2.105.2+rev1 \n \l
```
Maybe we update the test so that it doesn't care for this extra stuff?

**Comment by acostach** [comment]
thanks @rcooke-warwick , so the BBMASK does not work properly in this PR, I will do a local build and see what happens. We shouldn't include those BSP default ascii art, so no need to update the tests.

**Comment by acostach** [comment]
```
jenkins-leviathan-v2-template-5333-client-1  |             ok 1 - issue should contain distribution balenaOS
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:31.335Z][4b4ab6f-os]             ok 2 - issue should contain version 2.105.2+rev1
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:31.336Z][4b4ab6f-os]             1..2
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:31.336Z][4b4ab6f-os]         ok 1 - issue file check # time=23332.041ms
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.743Z][4b4ab6f-os]         # Subtest: issue.net file check
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.744Z][4b4ab6f-os]             ok 1 - issue.net should contain distribution balenaOS
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.744Z][4b4ab6f-os]             ok 2 - issue.net should contain version 2.105.2+rev1
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.744Z][4b4ab6f-os]             1..2
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.744Z][4b4ab6f-os]         ok 2 - issue.net file check # time=22405.627ms
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.744Z][4b4ab6f-os] 
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.745Z][4b4ab6f-os]         1..2
jenkins-leviathan-v2-template-5333-client-1  | [2022-09-28T13:47:53.745Z][4b4ab6f-os]     ok 4 - issue tests # time=45745.603ms
```

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
