### PR TITLE
linux-variscite: Add CW2015 battery driver for NRT

### PR DESCRIPTION
**Pull request by acostach**
Changelog-entry: linux-variscite: Add CW2015 battery driver for NRT
Signed-off-by: Alexandru Costache <alexandru@balena.io>

Addresses: https://github.com/balena-os/balena-variscite-mx8/issues/183

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@rcooke-warwick this DT does not have an eth port, nor am usb port to plug the eth cable, only wifi. Do the tests fail here because if the internet connectivity?

**Comment by rcooke-warwick** [comment]
@acostach you're using the current sensor to detect the poweroff right? No ethernet shouldn't be  problem here.

I can't see the test logs from this PR, where is it failing?

**Comment by rcooke-warwick** [comment]
@acostach I took a look at another test tun ( I will mark it as keep forever so it won't disappear and we can talk about it: https://jenkins.product-os.io/job/leviathan-v2-template/5223/

The DUT passed the cloud and HUP suites, however it fails at the issue check test:
```
# Subtest: issue tests
        # Subtest: issue file check
            not ok 1 - Cannot read property '1' of null
              ---
              stack: |
                /data/suite/tests/issue/index.js:44:30
                Array.forEach (<anonymous>)
                Proxy.run (/data/suite/tests/issue/index.js:42:22)
              at:
                line: 44
                column: 30
                file: /data/suite/tests/issue/index.js
              type: TypeError
              test: issue file check
              source: |
                					const parse = /(\S*)\s(\S*)/.exec(element);
                					result['distro'] = parse[1];
                -----------------------------^
                					result['version'] = parse[2];
                				});
              ...
```

I'm looking at what that is now - it might be that `/etc/issue` isn't right

**Comment by rcooke-warwick** [comment]
just checked, and indeed:
```
root@c71534d:~# cat /etc/issue

````
It is an empty file

**Comment by acostach** [comment]
@rcooke-warwick I raised https://github.com/balena-os/balena-variscite-mx8/pull/208 for the /etc/issue problem

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
